platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcc

inputs:
- name: wrk-git-src

outputs:
- name: wrk-binary

run:
  path: sh
  args:
  - -exc
  - |
    cd wrk-git-src
    make
    cp wrk ../wrk-binary/
