resources:
- name: concourse-configs 
  type: git
  source:
    uri: https://github.com/lcrisci/continuous-delivery.git
    branch: master
- name: wrk-git-src 
  type: git
  source:
    uri: https://github.com/wg/wrk.git
    branch: master

jobs:
  - name: build 
    plan:
      - get: wrk-git-src
      - get: concourse-configs 
      - task: build 
        file: concourse-configs/concourse/wrk-pipeline-configs/build.yml

  - name: package
    plan:
      - get: concourse-configs 
        passed: [ build ] 
      - task: package 
        file: concourse-configs/concourse/wrk-pipeline-configs/package.yml

  - name: deploy-dev
    plan:
      - get: concourse-configs 
        passed: [ package ] 
      - task: deploy-dev 
        file: concourse-configs/concourse/wrk-pipeline-configs/deploy-dev.yml

  - name: deploy-stg
    plan:
      - get: concourse-configs 
        passed: [ deploy-dev ] 
      - task: deploy-stg 
        file: concourse-configs/concourse/wrk-pipeline-configs/deploy-stg.yml

  - name: deploy-prd
    plan:
      - get: concourse-configs 
        passed: [ deploy-stg ] 
      - task: deploy-prd
        file: concourse-configs/concourse/wrk-pipeline-configs/deploy-prd.yml

groups:
- name: WRK 
  jobs:
  - build
  - package
  - deploy-dev
  - deploy-stg
  - deploy-prd
